using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyCompanyAttribute("CFT & ACM")]
[assembly: AssemblyVersionAttribute("0.8.0.46")]
[assembly: AssemblyFileVersionAttribute("0.8.0.46")]
[assembly: AssemblyInformationalVersionAttribute("0.8.0.g40422a84640e720d27fcd19daebad5f1c2199283")]
[assembly: AssemblyTitleAttribute("MassTransit")]
[assembly: AssemblyProductAttribute("MassTransit")]
[assembly: AssemblyDescriptionAttribute("MassTransit is a product of CFT & ACM. See more at http://masstransit-project.com" +
    "")]
[assembly: AssemblyTrademarkAttribute("MassTransit - CFT & ACM")]
[assembly: AssemblyCopyrightAttribute("Copyright 2011 CFT & ACM, - Original author or authors")]

